AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - '**/bin/**/*'
    - 'vendor/**/*'
    - 'gemfiles/vendor/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'Guardfile'

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

Rails/Blank:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/FileName:
  Exclude: ['Gemfile', 'Gemfile.lock', 'Appraisals']

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/SignalException:
  EnforcedStyle: only_raise

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedLastArgumentHashStyle: always_ignore

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false
